version: '3'

services:

#  app:
#    build: .
#    container_name: search-java-example
#    image: felipegirotti/search-java-example
#    depends_on:
#      - elasticsearch
#      - rabbitmq
#    env_file:
#      - .env
#    ports:
#      - "8081:8081"
#      - "8082:8082"

  elasticsearch:
    container_name: search-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ./docker/es/data:/usr/share/elasticsearch/data:cached
    ports:
    - 9200:9200

  rabbitmq:
    container_name: drz-rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
    - "${RABBITMQ_ADMIN_PORT}:15672"
    - "5672:5672"



